# Generated by Django 4.1.2 on 2022-11-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('주택명', models.CharField(max_length=20)),
                ('모집공고일', models.CharField(max_length=20)),
                ('청약접수시작일', models.CharField(max_length=20)),
                ('당첨자발표일', models.CharField(max_length=20)),   
                ('계약시작일', models.CharField(max_length=20)),
                ('입주예정월', models.CharField(max_length=20)),
                ('위도', models.FloatField()),
                ('경도', models.FloatField()),
                ('공급위치', models.CharField(max_length=30)),
                ('공급규모', models.FloatField()),
            ],
        ),
    ]
