# Generated by Django 4.1.2 on 2022-11-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='maket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('번호', models.FloatField()),
                ('시장명', models.CharField(max_length=30)),
                ('시장유형', models.CharField(max_length=10)),
                ('위도', models.FloatField()),
                ('경도', models.FloatField()),
                ('소재지도로명주소', models.CharField(max_length=30)),
                ('시장개설주기', models.CharField(max_length=10)),
                ('소재지지번주소', models.CharField(max_length=30)),
                ('점포수', models.FloatField()),
                ('사용가능상품권', models.CharField(max_length=20)),
                ('공중화장실보유여부', models.CharField(max_length=5)),
                ('주차장보유여부', models.CharField(max_length=5)),
                ('개설년도', models.FloatField()),
            ],
        ),
    ]
