# Generated by Django 4.1.2 on 2022-11-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_maket'),
    ]

    operations = [
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('번호', models.FloatField()),
                ('학교ID', models.FloatField()),
                ('학교명', models.CharField(max_length=20)),
                ('학교급구분', models.CharField(max_length=10)),
                ('설립일자', models.CharField(max_length=30)),
                ('설립형태', models.CharField(max_length=10)),
                ('소재지지번주소', models.CharField(max_length=30)),
                ('소재지도로명주소', models.CharField(max_length=30)),
                ('위도', models.FloatField()),
                ('경도', models.FloatField()),
            ],
        ),
    ]
