# Generated by Django 4.1.2 on 2022-11-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('관리번호', models.CharField(max_length=20)),
                ('공원명', models.CharField(max_length=30)),
                ('공원구분', models.CharField(max_length=20)),
                ('소재지지번주소', models.CharField(max_length=30)),
                ('위도', models.FloatField()),
                ('경도', models.FloatField()),
            ],
        ),
    ]
